[package]
name = "amitoki-l3-lab"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4", features = ["derive"] }
libc = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }

[[bin]]
name = "amitoki-l3"
path = "src/main.rs"

[[bin]]
name = "amitoki-l3-udp"
path = "src/udp_main.rs"

[[bin]]
name = "amitoki-l3-tcp"
path = "src/tcp_main.rs"
